Lab.EF/Lab.EF.MVC/Controllers/SuppliersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab.EF.Entities;
using Lab.EF.Logic;
using Lab.EF.MVC.Models;

namespace Lab.EF.MVC.Controllers
{
    public class SuppliersController : Controller
    {
        private readonly SuppliersLogic _suppliersLogic;

        public SuppliersController()
        {
            _suppliersLogic = new SuppliersLogic();
        }

        // GET: Suppliers
        public ActionResult Index()
        {
            List<SuppliersView> suppliers = _suppliersLogic.GetAll().Select(s => new SuppliersView
            {
                Id = s.SupplierID,
                CompanyName = s.CompanyName,
                ContactName = s.ContactName,
                ContactTitle = s.ContactTitle,
                Address = s.Address,
                City = s.City,
                Country = s.Country
            }).ToList();

            return View(suppliers);
        }

        public ActionResult Add()
        {
            ViewData["Action"] = "Add";
            ViewData["BtnText"] = "Crear proveedor";

            return View("FormSupplier", new SuppliersView());
        }

        [HttpPost]
        public ActionResult Add(SuppliersView supplierView)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Action"] = "Add";
                ViewData["BtnText"] = "Crear proveedor";

                return View("FormSupplier", supplierView);
            }

            try
            {
                Suppliers supplier = new Suppliers()
                {
                    CompanyName = supplierView.CompanyName,
                    ContactName = supplierView.ContactName,
                    ContactTitle = supplierView.ContactTitle,
                    Address = supplierView.Address,
                    City = supplierView.City,
                    Country = supplierView.Country
                };

                _suppliersLogic.Add(supplier);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", new { message = ex.Message });
            }
        }

        public ActionResult Update(int id)
        {
            Suppliers supplier = _suppliersLogic.GetById(id);

            if (supplier == null) return RedirectToAction("Error", new { message = $"El proveedor con el id {id} no existe." });

            SuppliersView supplierView = new SuppliersView()
            {
                Id = supplier.SupplierID,
                CompanyName = supplier.CompanyName,
                ContactName = supplier.ContactName,
                ContactTitle = supplier.ContactTitle,
                Address = supplier.Address,
                City = supplier.City,
                Country = supplier.Country
            };

            ViewData["Action"] = "Update";
            ViewData["BtnText"] = "Actualizar proveedor";

            return View("FormSupplier", supplierView);
        }

        [HttpPost]
        public ActionResult Update(SuppliersView supplierView)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Action"] = "Update";
                ViewData["BtnText"] = "Actualizar proveedor";

                return View("FormSupplier", supplierView);
            }

            try
            {
                Suppliers supplier = new Suppliers()
                {
                    SupplierID = supplierView.Id,
                    CompanyName = supplierView.CompanyName,
                    ContactName = supplierView.ContactName,
                    ContactTitle = supplierView.ContactTitle,
                    Address = supplierView.Address,
                    City = supplierView.City,
                    Country = supplierView.Country
                };


                _suppliersLogic.Update(supplier);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", new { message = ex.Message });
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                _suppliersLogic.Delete(id);

                return RedirectToAction("Index");
            }
            catch (ArgumentNullException ex)
            {
                return RedirectToAction("Error", new { message = $"El proveedor con el id {id} no existe." });
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", new { message = ex.Message });
            }
        }

        public ActionResult Error(string message)
        {
            ViewBag.Message = message;
            return View();
        }
    }
}

Lab.EF/Lab.EF.MVC/Views/Suppliers/FormSupplier.cshtml
@model Lab.EF.MVC.Models.SuppliersView
@{
    ViewBag.Title = ViewData["BtnText"];
}

<div class="card m-auto my-4">
    <h3>@ViewBag.Title</h3>
    @using (Html.BeginForm(ViewData["Action"].ToString(), "Suppliers", FormMethod.Post))
    {
        <div class="inputbox">
            @Html.TextBoxFor(m => m.CompanyName, new { @class = "form-control" })
            <span class="inputspan">Nombre de la compañia</span>
            @Html.ValidationMessageFor(m => m.CompanyName, "", new { @class = "text-danger mt-4 d-block" })
        </div>
        <div class="inputbox">
            @Html.TextBoxFor(m => m.ContactName, new { @class = "form-control" })
            <span class="inputspan">Nombre del contacto</span>
            @Html.ValidationMessageFor(m => m.ContactName, "", new { @class = "text-danger mt-4 d-block" })
        </div>
        <div class="inputbox">
            @Html.TextBoxFor(m => m.ContactTitle, new { @class = "form-control" })
            <span class="inputspan">Titulo del contacto</span>
        </div>
        <div class="inputbox">
            @Html.TextBoxFor(m => m.City, new { @class = "form-control" })
            <span class="inputspan">Ciudad</span>
        </div>
        <div class="inputbox">
            @Html.TextBoxFor(m => m.Country, new { @class = "form-control" })
            <span class="inputspan">País</span>
        </div>

        <input type="submit" value="@ViewData["BtnText"]" class="btn btn-primary btn-block d-block" />
        @Html.ActionLink("Volver atrás", "Index", "Suppliers", new { @class = "btn text-primary text-decoration-underline btn-block p-0 mt-1" })
    }
</div>

Lab.EF/Lab.EF.MVC/Views/Suppliers/Index.cshtml
@model List<Lab.EF.MVC.Models.SuppliersView>
@{
    ViewBag.Title = "Proveedores";
}

<h2 class="mb-4 mt-0 pt-0 text-center">Proveedores</h2>

@Html.ActionLink(" Añadir proveedor", "Add", new { }, new { @class = "btn btn-success bi-plus-circle", title = "Añadir proveedor" })

<table class="table table-hover my-3 bg-white">
    <thead>
        <tr class="bg-primary text-white">
            <th>Proveedor</th>
            <th>Ciudad</th>
            <th>País</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Lab.EF.MVC.Models.SuppliersView supplier in Model)
        {
            <tr>
                <td class="fw-bold">@supplier.CompanyName</td>
                <td>@supplier.City</td>
                <td>@supplier.Country</td>
                <td>
                    @Html.ActionLink(" ", "Update", new { id = supplier.Id }, new { @class = "btn btn-warning rounded-circle bi-pencil-square text-white", title = "Actualizar proveedor" })
                    <button class="btn btn-danger rounded-circle bi-trash"
                            onclick="mostrarAlerta('Suppliers', 'Delete', @supplier.Id, '¿Estás seguro que deseas eliminar el proveedor?')"></button>
                </td>
            </tr>
        }
    </tbody>
</table>